language: c
sudo: true
env:
  - PROD=1 TEST_VERBOSE=1 ORION_PATH="./orion"
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install libmatio-dev pdl libinline-perl
  - sudo apt-get build-dep pdl
  - curl -L https://cpanmin.us | perl - --sudo App::cpanminus
  - git clone https://github.com/CBL-ORION/ITK-builds.git external/ITK
  # path for CMake to search for built ITK
  - export ITK_DIR="`( cd external/ITK/usr/local/lib/cmake/ITK-4.9 && pwd )`"
script:
  # version of gcc on Travis-CI does not support ASAN flag
  - if [ "$CC" = "clang" ]; then export CXX="clang++"; fi
  - if [ "$CC" = "gcc" ]; then export BUILD_ENABLE_ASAN=0; else export BUILD_ENABLE_ASAN=1; fi
  - ./build-liborion
  - sudo make dep.perl
  - prove -lvr t
branches:
  except:
    - /^wip\//
    - /^blocked/
